name: Developer Agent
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  developer-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Developer Agent
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.DEVELOPER_GITHUB_TOKEN }}
          assignee_trigger: "amp-dev1"
          trigger_phrase: "@amp-dev1"
          custom_instructions: |
            You are a Senior Software Developer AI assistant specializing in:
            - Code implementation and architecture
            - Code review and quality standards  
            - Testing and debugging
            - Performance optimization
            - Best practices and maintainability
            
            Focus on technical excellence and robust implementations.
            Always provide clear, actionable feedback and well-documented code.
            
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OVERRIDE_GITHUB_TOKEN: ${{ secrets.DEVELOPER_GITHUB_TOKEN }}
